import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useTranslation } from "react-i18next";
import { api } from "@/utils/api";

export default function Home() {
  const { t } = useTranslation();

  const { data: sessionData } = useSession();

  const renderSignIn = () => (
    <div>
      <h1>{t("signIn")}</h1>
    </div>
  );
  return (
    <>
      <Head>
        <title>Notekeeper - Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" dark:bg-midnight flex min-h-screen flex-col items-center justify-center bg-white">
        {!sessionData && renderSignIn()}
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={
          sessionData ? () => void signOut() : () => void signIn("github")
        }
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
