name: tests

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Intalling Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.

      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Run unit Tests
        run: pnpm test

      - name: Build
        run: pnpm build
